<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <PublishReadyToRun>true</PublishReadyToRun>
	  <PublishTrimmed>false</PublishTrimmed>
	  <ApplicationIcon>resources/app.ico</ApplicationIcon>
	  <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.1" />
  </ItemGroup>

</Project>
